/*
 * Post-build step: injects a content-derived version and the precache manifest into
 * dist/sw.js.
 *
 * Vite emits content-hashed filenames, so the service worker cannot know them ahead of
 * time. Without this, the worker can only cache assets after a user has already
 * requested them — the first offline load of an unvisited route would fail. Deriving
 * the version from the asset list also means a deploy that changes nothing produces
 * the same cache name, so users aren't forced through a pointless cache eviction.
 *
 * Runs automatically via `npm run build`.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DIST = path.join(__dirname, '..', 'dist');
const SW_PATH = path.join(DIST, 'sw.js');

if (!fs.existsSync(SW_PATH)) {
    console.error(`[build-sw] ${SW_PATH} not found — did vite build run?`);
    process.exit(1);
}

// Everything worth having available on a cold offline start.
const collect = (dir, prefix = '') => {
    if (!fs.existsSync(dir)) return [];
    return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const rel = `${prefix}/${entry.name}`;
        return entry.isDirectory() ? collect(path.join(dir, entry.name), rel) : [rel];
    });
};

const assets = collect(path.join(DIST, 'assets'), '/assets');
const icons = collect(path.join(DIST, 'icons'), '/icons');

const precache = [
    '/index.html',
    '/offline.html',
    '/manifest.json',
    ...assets,
    ...icons
];

const version = crypto
    .createHash('sha256')
    .update(precache.join('|'))
    .digest('hex')
    .slice(0, 12);

const banner =
    `// Generated by scripts/build-sw.cjs — do not edit dist/sw.js directly.\n` +
    `self.__SW_VERSION__ = ${JSON.stringify(version)};\n` +
    `self.__PRECACHE__ = ${JSON.stringify(precache)};\n\n`;

const source = fs.readFileSync(SW_PATH, 'utf8');

if (source.includes('self.__SW_VERSION__ =')) {
    console.log('[build-sw] banner already present, skipping');
    process.exit(0);
}

fs.writeFileSync(SW_PATH, banner + source);

console.log(`[build-sw] version ${version}, precaching ${precache.length} entries ` +
    `(${assets.length} assets, ${icons.length} icons)`);
